Patch again
mdolab/MACH-Aero pull request #29
Opened 2021-01-13 04:20 UTC by galenng525

## Purpose
These are definitely minor edits but I think they can make it more foolproof (but they always invent a better fool). Just combing through as I go.

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- Documentation update
- 
## Testing
Explain the steps needed to test the new code to verify that it does indeed address the issue and produce the expected behavior.

## Checklist
_Put an `x` in the boxes that apply._

- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ x] I have added necessary documentation

2021-01-13 04:52 UTC, nwu63 submitted a review, later dismissed
Fine with this, but if there are more updates it may be better to do everything at once rather than submitting a bunch of small PRs.

2021-01-13 09:35 UTC, marcomangano requested changes
Yeah I agree with Neil, this is good work but we might want to wait to merge so you can finish the tutorial and push all the corrections at once

2021-01-26 05:04 UTC, galenng525 commented
Finished.

2021-01-26 09:55 UTC, marcomangano approved these changes

2021-01-26 09:55 UTC, merged